import { AIChatBox, type Message } from "@/components/AIChatBox";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { BookOpenText, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function AskMode() {
  const [messages, setMessages] = useState<Message[]>([]); const [citations, setCitations] = useState<{ findingId: number; title: string; url: string }[]>([]); const [conversationId, setConversationId] = useState<number>();
  const ask = trpc.intelligence.ask.query.useMutation({ onSuccess: response => { setConversationId(response.conversationId); setMessages(current => [...current, { role: "assistant", content: response.answer }]); setCitations(response.citations); }, onError: error => { setMessages(current => current.slice(0, -1)); toast.error(error.message); } });
  const send = (question: string) => { setMessages(current => [...current, { role: "user", content: question }]); ask.mutate({ question, conversationId }); };
  return <div className="mx-auto max-w-[1280px] space-y-7 pb-12"><header className="border-b border-slate-200/70 pb-7"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-violet-600">Knowledge retrieval</p><h1 className="font-display text-3xl font-semibold tracking-[-0.035em] text-slate-950">Ask Mode</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Ask a question of your accumulated research. Every answer is constrained to the source records Intelis has collected.</p></header><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_310px]"><AIChatBox messages={messages} onSendMessage={send} isLoading={ask.isPending} height="620px" placeholder="Ask about your research…" emptyStateMessage="Your research base is ready for a question." suggestedPrompts={["What are the most important changes in my research?", "Which entities are appearing across multiple sources?", "What evidence is strongest in the latest findings?"]} className="border-slate-200/90 shadow-[0_6px_28px_rgb(15_23_42/0.06)]" /><aside className="space-y-4"><div className="rounded-2xl bg-[#10142a] p-5 text-white"><Sparkles className="h-4 w-4 text-violet-300" /><h2 className="mt-4 text-sm font-semibold">Grounded answers</h2><p className="mt-2 text-xs leading-5 text-slate-300">Intelis selects research records first, then asks the model to answer only from that evidence.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><BookOpenText className="h-4 w-4 text-violet-600" /><h2 className="text-sm font-semibold text-slate-800">Evidence cited</h2></div><div className="mt-4 space-y-3">{citations.length ? citations.map(citation => <a key={citation.findingId} href={citation.url} target="_blank" rel="noreferrer" className="block rounded-xl border border-slate-100 p-3 transition-colors hover:bg-slate-50"><p className="line-clamp-2 text-xs font-medium leading-5 text-slate-700">{citation.title}</p><p className="mt-2 text-[10px] text-violet-600">Open source ↗</p></a>) : <p className="text-xs leading-5 text-slate-400">Citations for the latest answer will appear here.</p>}</div></div></aside></div></div>;
}
